# example netlify.toml
[build]
  command = "yarn build"
  functions = "lambda" #  netlify-lambda reads this
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*/edit"
  to = "/"
  status = 200

[[redirects]]
  from = "/static/*"
  to = "/static/:splat"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/render?guid=:splat"
  status = 200

[[headers]]
  for = "*.js" 
  [headers.values]
    Cache-Control = "public, max-age=604800"
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=604800"